/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studyassist;

import static com.mycompany.studyassist.ExportOrNot.ExportQuestionPopup;
import static com.mycompany.studyassist.importExportMarks.arrayAdder;
import static com.mycompany.studyassist.removeMark.removeThatMark;
import static com.mycompany.studyassist.searchMark.markFinder;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

/**
 *
 * @author alex_
 */
public class Gui extends javax.swing.JFrame {
    static ArrayList<Mark> markArr = new ArrayList<>();
    ArrayList<String> topCourses;
    ArrayList<Double> topAverages;
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        courseCodeField = new javax.swing.JScrollPane();
        courseCodeTextField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JScrollPane();
        nameTextField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        givenThinkingField = new javax.swing.JScrollPane();
        givenThinkingTextField = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        givenKnowleadgeField = new javax.swing.JScrollPane();
        givenKnowledgeTextField = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        maxThinkingFIeld = new javax.swing.JScrollPane();
        maxThinkingTextField = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        maxKnowleadgeField = new javax.swing.JScrollPane();
        maxKnowledgeTextField = new javax.swing.JTextArea();
        maxCommunicationField = new javax.swing.JScrollPane();
        maxCommunicationTextField = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        givenCommunicationTextField = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        maxApplicationTextField = new javax.swing.JTextArea();
        givenApplicationField = new javax.swing.JScrollPane();
        givenApplicationTextField = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        addMarkButton = new java.awt.Button();
        searchMarkButton = new java.awt.Button();
        overallAverageButton = new java.awt.Button();
        top6AverageButton = new java.awt.Button();
        removeMarkButton = new java.awt.Button();
        exitButton = new java.awt.Button();
        jLabel14 = new javax.swing.JLabel();
        maxKnowleadgeField1 = new javax.swing.JScrollPane();
        weightKnowledgeTextField = new javax.swing.JTextArea();
        maxCommunicationField1 = new javax.swing.JScrollPane();
        weightApplicationTextField = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        weightCommunicationField = new javax.swing.JScrollPane();
        weightCommunicationTextField = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        maxThinkingFIeld1 = new javax.swing.JScrollPane();
        weightThinkingTextField = new javax.swing.JTextArea();
        courseAverageButton = new java.awt.Button();
        displayMarkButton = new java.awt.Button();
        maxCommunicationField2 = new javax.swing.JScrollPane();
        maxCulminatingTextField = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        weightCommunicationField1 = new javax.swing.JScrollPane();
        givenCulminatingTextField = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        weightCulminatingField = new javax.swing.JScrollPane();
        weightCulminatingTextField = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("StudyAssist");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setAutoscrolls(true);

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        courseCodeTextField.setColumns(5);
        courseCodeTextField.setRows(1);
        courseCodeField.setViewportView(courseCodeTextField);

        jLabel2.setText("Course Code");

        nameTextField.setColumns(5);
        nameTextField.setRows(1);
        nameField.setViewportView(nameTextField);

        jLabel3.setText("Assignment Name");

        jLabel5.setText("Given Knowledge");

        givenThinkingTextField.setColumns(5);
        givenThinkingTextField.setRows(1);
        givenThinkingField.setViewportView(givenThinkingTextField);

        jLabel7.setText("Given Thinking");

        givenKnowledgeTextField.setColumns(5);
        givenKnowledgeTextField.setRows(1);
        givenKnowleadgeField.setViewportView(givenKnowledgeTextField);

        jLabel8.setText("Given Application");

        maxThinkingTextField.setColumns(5);
        maxThinkingTextField.setLineWrap(true);
        maxThinkingTextField.setRows(1);
        maxThinkingFIeld.setViewportView(maxThinkingTextField);

        jLabel9.setText("Max Thinking");

        maxKnowledgeTextField.setColumns(5);
        maxKnowledgeTextField.setRows(1);
        maxKnowleadgeField.setViewportView(maxKnowledgeTextField);

        maxCommunicationTextField.setColumns(5);
        maxCommunicationTextField.setRows(1);
        maxCommunicationField.setViewportView(maxCommunicationTextField);

        jLabel10.setText("Max Communication");

        givenCommunicationTextField.setColumns(5);
        givenCommunicationTextField.setRows(1);
        jScrollPane11.setViewportView(givenCommunicationTextField);

        jLabel11.setText("Max Knowledge");

        jLabel12.setText("Given Communication");

        maxApplicationTextField.setColumns(5);
        maxApplicationTextField.setRows(1);
        jScrollPane12.setViewportView(maxApplicationTextField);

        givenApplicationTextField.setColumns(5);
        givenApplicationTextField.setRows(1);
        givenApplicationField.setViewportView(givenApplicationTextField);

        jLabel13.setText("Max Application");

        addMarkButton.setLabel("Add Mark");
        addMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarkButtonActionPerformed(evt);
            }
        });

        searchMarkButton.setLabel("Search Mark");
        searchMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMarkButtonActionPerformed(evt);
            }
        });

        overallAverageButton.setLabel("Overall Average");
        overallAverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallAverageButtonActionPerformed(evt);
            }
        });

        top6AverageButton.setLabel("Top 6 Average");
        top6AverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top6AverageButtonActionPerformed(evt);
            }
        });

        removeMarkButton.setLabel("Remove Mark");
        removeMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMarkButtonActionPerformed(evt);
            }
        });

        exitButton.setActionCommand("Exit and Export");
        exitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        exitButton.setLabel("Exit and Export");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Weight Thinking");

        weightKnowledgeTextField.setColumns(5);
        weightKnowledgeTextField.setRows(1);
        maxKnowleadgeField1.setViewportView(weightKnowledgeTextField);

        weightApplicationTextField.setColumns(5);
        weightApplicationTextField.setRows(1);
        maxCommunicationField1.setViewportView(weightApplicationTextField);

        jLabel15.setText("Weight Communication");

        jLabel16.setText("Weight Knowledge");

        weightCommunicationTextField.setColumns(5);
        weightCommunicationTextField.setRows(1);
        weightCommunicationField.setViewportView(weightCommunicationTextField);

        jLabel17.setText("Weight Application");

        weightThinkingTextField.setColumns(5);
        weightThinkingTextField.setLineWrap(true);
        weightThinkingTextField.setRows(1);
        maxThinkingFIeld1.setViewportView(weightThinkingTextField);

        courseAverageButton.setLabel("Course Average");
        courseAverageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseAverageButtonActionPerformed(evt);
            }
        });

        displayMarkButton.setLabel("Display All Marks");
        displayMarkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMarkButtonActionPerformed(evt);
            }
        });

        maxCulminatingTextField.setColumns(5);
        maxCulminatingTextField.setRows(1);
        maxCommunicationField2.setViewportView(maxCulminatingTextField);

        jLabel18.setText("Given Culminating");

        givenCulminatingTextField.setColumns(5);
        givenCulminatingTextField.setRows(1);
        weightCommunicationField1.setViewportView(givenCulminatingTextField);

        jLabel19.setText("Max Culminating");

        weightCulminatingTextField.setColumns(5);
        weightCulminatingTextField.setLineWrap(true);
        weightCulminatingTextField.setRows(1);
        weightCulminatingField.setViewportView(weightCulminatingTextField);

        jLabel20.setText("Weight Culminating");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(weightCommunicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maxCommunicationField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(maxThinkingFIeld1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maxKnowleadgeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(courseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(givenApplicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maxCommunicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(givenThinkingField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(givenKnowleadgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(maxThinkingFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(maxKnowleadgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(maxCommunicationField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(weightCulminatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(weightCommunicationField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(courseAverageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(top6AverageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(removeMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(displayMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(overallAverageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(courseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(givenKnowleadgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(givenThinkingField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(givenApplicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(weightCommunicationField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(maxCommunicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxThinkingFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxKnowleadgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxCommunicationField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxKnowleadgeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(weightCommunicationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxThinkingFIeld1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxCommunicationField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(weightCulminatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseAverageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(top6AverageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overallAverageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(removeMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(displayMarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseAverageButtonActionPerformed(ActionEvent evt) {
        // Define variables and get the course average that need to be searched
        String course = courseCodeTextField.getText();
        double dailyMark = 0;
	double culminatingMark = 0;
        double dailyWeight = 0;
        double culminatingWeight = 0;
        // To check if the course was found in the array
        boolean found = false;
        String text = "";
        
        // Average Calculation when assuming the ktca sections are weighted equally
        // Loop through the array list to calculate the weighted marks and weights
        for (Mark item : markArr) {
            /// Compare course codes to find the matching course
            String courseCode = item.getCourseCode();
            if (course.equals(courseCode)) {
                found = true;
                // Accumulate the weighted marks and weights 
		dailyMark = dailyMark + item.getKMark() / item.getKMaxMark() * item.getKWeight();
		dailyMark = dailyMark + item.getTMark() / item.getTMaxMark() * item.getTWeight();
		dailyMark = dailyMark + item.getCMark() / item.getCMaxMark() * item.getCWeight();
		dailyMark = dailyMark + item.getAMark() / item.getAMaxMark() * item.getAWeight();
                dailyWeight = dailyWeight + item.getKWeight() + item.getTWeight() + item.getCWeight() + item.getAWeight();
		culminatingMark = culminatingMark + item.getCulminatingMark() / item.getCulminatingMaxMark() * item.getCulminatingWeight();
                culminatingWeight = culminatingWeight + item.getCulminatingWeight();
		}
	}
        
        // Calculate the averages if the weights are valid
        double dailyAverage = dailyMark / dailyWeight * 100;
        double culminatingAverage = culminatingMark / culminatingWeight * 100;
        double courseAverage = dailyAverage * 0.7 + culminatingAverage * 0.3;
        
        // Display a message if the course was not found
        if (!found) {
            display.setText("The course is not found.");
            return;
        }
        
        // Check for invalid weights and display according messages
        if (dailyWeight <= 0 || culminatingWeight <= 0){
            if (dailyWeight <= 0){
                text += "You don't have any assignments with weightings in KTCA.\n";
                text += String.format("Course Code: %s\nDaily Average: N/A\nCulminating Average: %.1f%%\nCourse Average: %.1f%%",
                course, culminatingAverage,culminatingAverage);
            }
            if (culminatingWeight <= 0){
                text += "You don't have any assignments with culminating weightings.\n";
                text += String.format("Course Code: %s\nDaily Average: %.1f%%\nCulminating Average: N/A\nCourse Average: %.1f%%",
                course,dailyAverage, dailyAverage);
            }
            if (dailyWeight <= 0 && culminatingWeight <= 0){
                text += "None of your assignments have any weightings. Average is not applicable.";
            }
        } else {
            // Display the calculated averages if weights are valid
            text += String.format("Course Code: %s\nDaily Average: %.1f%%\nCulminating Average: %.1f%%\nCourse Average: %.1f%%",
                    course,dailyAverage, culminatingAverage,courseAverage);
        }        
        
        // Display the result text
        display.setText(text);
    }

    private void displayMarkButtonActionPerformed(ActionEvent evt) {
        // Define a beginning text
        String text = "All Existing Assignments:\n";
        
        // Add all attributes of each mark into the text in clear format
        for (Mark item : markArr){
            text += "Course code: " + item.getCourseCode() + " ";
            text += "Assignment name: " + item.getAssignmentName() + "\n";
            text += String.format("Knowledge - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", item.getKMark(), item.getKMaxMark(), item.getKWeight());
            text += String.format("Thinking - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", item.getTMark(), item.getTMaxMark(), item.getTWeight());
            text += String.format("Communication - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", item.getCMark(), item.getCMaxMark(), item.getCWeight());
            text += String.format("Application - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", item.getAMark(), item.getAMaxMark(), item.getAWeight());
            text += String.format("Culminating - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", item.getCulminatingMark(), item.getCulminatingMaxMark(), item.getCulminatingWeight());
            text += "\n";
        }
        // Display text
        display.setText(text);
    }

    private void addMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarkButtonActionPerformed
        // TODO add your handling code here:
        // Report error and return if any field is empty
        if (courseCodeTextField.getText().isEmpty() || nameTextField.getText().isEmpty() || givenKnowledgeTextField.getText().isEmpty() || maxKnowledgeTextField.getText().isEmpty() 
            || weightKnowledgeTextField.getText().isEmpty() || givenThinkingTextField.getText().isEmpty() || maxThinkingTextField.getText().isEmpty() || weightThinkingTextField.getText().isEmpty()
            || givenCommunicationTextField.getText().isEmpty() || maxCommunicationTextField.getText().isEmpty() || weightCommunicationTextField.getText().isEmpty() || givenApplicationTextField.getText().isEmpty()
            || maxApplicationTextField.getText().isEmpty() || weightApplicationTextField.getText().isEmpty() || givenCulminatingTextField.getText().isEmpty() || maxCulminatingTextField.getText().isEmpty()
            || weightCulminatingTextField.getText().isEmpty()) {
            display.setText("You left a piece of information empty. \nSet the weight as 0 if you don't have a mark for any sections on the assignment.");
            return;
        }
        // Trim and get the course code and assignment name
        String courseCode = courseCodeTextField.getText().trim();
	String assignmentName = nameTextField.getText().trim();
        
        // Check if course code or assignment name contains only numbers
        if (stringCheck(courseCode) || stringCheck(assignmentName)){
            display.setText("Your course code or assignment name cannot be pure numbers.");
            return;
        }
        
        // Check if course code or assignment name contains only numbers
        if (assignmentExists(courseCode, assignmentName)){
            display.setText("The assignment already exists in this course.");
            return;
        }
        
        try{
            // Parse and validate each section's inputs
            double kMark = Double.parseDouble(givenKnowledgeTextField.getText().trim());
            double kMaxMark = Double.parseDouble(maxKnowledgeTextField.getText().trim());
            double kWeight = Double.parseDouble(weightKnowledgeTextField.getText().trim());
		
            if (kMark < 0 || kWeight < 0 || kMaxMark < kMark) {
                display.setText("Invalid input for Knowledge section. Ensure marks are non-negative, weights are non-negative, and max marks are greater than or equal to given marks.");
                return;
            }
        
            double tMark = Double.parseDouble(givenThinkingTextField.getText().trim());
            double tMaxMark = Double.parseDouble(maxThinkingTextField.getText().trim());
            double tWeight = Double.parseDouble(weightThinkingTextField.getText().trim());
		
            if (tMark < 0 || tWeight < 0 || tMaxMark < tMark) {
                display.setText("Invalid input for Thinking section. Ensure marks are non-negative, weights are non-negative, and max marks are greater than or equal to given marks.");
                return;
            }
        
            double cMark = Double.parseDouble(givenCommunicationTextField.getText().trim());
            double cMaxMark = Double.parseDouble(maxCommunicationTextField.getText().trim());
            double cWeight = Double.parseDouble(weightCommunicationTextField.getText().trim());
		
            if (cMark < 0 || cWeight < 0 || cMaxMark < tMark) {
                display.setText("Invalid input for Communication section. Ensure marks are non-negative, weights are non-negative, and max marks are greater than or equal to given marks.");
                return;
            }
        
            double aMark = Double.parseDouble(givenApplicationTextField.getText().trim());
            double aMaxMark = Double.parseDouble(maxApplicationTextField.getText().trim());
            double aWeight = Double.parseDouble(weightApplicationTextField.getText().trim());
		
            if (aMark < 0 || aWeight < 0 || aMaxMark < tMark) {
                display.setText("Invalid input for Application section. Ensure marks are non-negative, weights are non-negative, and max marks are greater than or equal to given marks.");
                return;
            }
               
            double culminatingMark = Double.parseDouble(givenCulminatingTextField.getText().trim());
            double culminatingMaxMark = Double.parseDouble(maxCulminatingTextField.getText().trim());
            double culminatingWeight = Double.parseDouble(weightCulminatingTextField.getText().trim());
                
            if (culminatingMark < 0 || culminatingWeight < 0 || culminatingMaxMark < tMark) {
                display.setText("Invalid input for Culminating section. Ensure marks are non-negative, weights are non-negative, and max marks are greater than or equal to given marks.");
                return;
            }
             
            // Create a new Mark object with the validated inputs
            Mark newMark = new Mark(courseCode, assignmentName, kMark, kMaxMark, kWeight, tMark, tMaxMark, tWeight, cMark, 
				cMaxMark, cWeight, aMark, aMaxMark, aWeight, culminatingMark, culminatingMaxMark, culminatingWeight);
		
            // Prepare the result text
            String text = "You added an assignment:\n";
            text += "Course code: " + newMark.getCourseCode() + " ";
            text += "Assignment name: " + newMark.getAssignmentName() + "\n";
            text += String.format("Knowledge - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", newMark.getKMark(), newMark.getKMaxMark(), newMark.getKWeight());
            text += String.format("Thinking - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", newMark.getTMark(), newMark.getTMaxMark(), newMark.getTWeight());
            text += String.format("Communication - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", newMark.getCMark(), newMark.getCMaxMark(), newMark.getCWeight());
            text += String.format("Application - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", newMark.getAMark(), newMark.getAMaxMark(), newMark.getAWeight());
            text += String.format("Culminating - Mark: %.1f, Max Mark: %.1f, Weight: %.1f\n", newMark.getCulminatingMark(), newMark.getCulminatingMaxMark(), newMark.getCulminatingWeight());
            
            // Display the result text and add mark to the array
            display.setText(text);
            markArr.add(newMark);
       
        } catch (NumberFormatException e) {
            // Display error if parsing fails
            display.setText("You must enter a number for the marks and weights.");
	}
    }//GEN-LAST:event_addMarkButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        ExportQuestionPopup();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void removeMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMarkButtonActionPerformed
        // TODO add your handling code here:
        removeThatMark();
    }//GEN-LAST:event_removeMarkButtonActionPerformed

    private void overallAverageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallAverageButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> allCourses = new ArrayList<>();
        ArrayList<Double> allAverages = new ArrayList<>();
        double overallAverage = 0;
        String text = "";
        
        for (Mark item : markArr){
            String course = item.getCourseCode();
            if (!allCourses.contains(course)){
                allCourses.add(course);
            }
        }
        
        if (allCourses.size() < 0){
            display.setText("You don't have any courses yet. Try again later.");
            return;
        }
        
        // Average Calculation when assuming the ktca sections are weighted equally
        for (String course : allCourses) {
            double dailyMark = 0;
            double culminatingMark = 0;
            double dailyWeight = 0;
            double culminatingWeight = 0;
            for (Mark item : markArr){
                if (course.equals(item.getCourseCode())) {
		dailyMark = dailyMark + item.getKMark() / item.getKMaxMark() * item.getKWeight();
		dailyMark = dailyMark + item.getTMark() / item.getTMaxMark() * item.getTWeight();
		dailyMark = dailyMark + item.getCMark() / item.getCMaxMark() * item.getCWeight();
		dailyMark = dailyMark + item.getAMark() / item.getAMaxMark() * item.getAWeight();
                dailyWeight = dailyWeight + item.getKWeight() + item.getTWeight() + item.getCWeight() + item.getAWeight();
                 
		culminatingMark = culminatingMark + item.getCulminatingMark() / item.getCulminatingMaxMark() * item.getCulminatingWeight();
                culminatingWeight = culminatingWeight + item.getCulminatingWeight();
		}
            }
            double dailyAverage = dailyMark / dailyWeight * 100;
            double culminatingAverage = culminatingMark / culminatingWeight * 100;
            double courseAverage = dailyAverage * 0.7 + culminatingAverage * 0.3;
            allAverages.add(courseAverage);
	}
        
        for (double average : allAverages){
            overallAverage += average;
        }
        overallAverage =  overallAverage / allCourses.size();
        
        for (int i = 0; i < allCourses.size(); i++){
            text += "Course code: " + allCourses.get(i) + " ";
            text += String.format("Course Average: %.1f\n", allAverages.get(i));
        }
        text += String.format("Overall Average: %.1f\n", overallAverage);
        
        display.setText(text);
    }//GEN-LAST:event_overallAverageButtonActionPerformed

    private void searchMarkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMarkButtonActionPerformed
        // TODO add your handling code here:
        markFinder();
    }//GEN-LAST:event_searchMarkButtonActionPerformed

    private void top6AverageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top6AverageButtonActionPerformed
        // TODO add your handling code here:
        topCourses = new ArrayList<>();
        topAverages = new ArrayList<>();
        double overallAverage = 0;
        String text = "";
        
        for (Mark item : markArr){
            String course = item.getCourseCode();
            if (!topCourses.contains(course)){
                topCourses.add(course);
            }
        }
        
        if (topCourses.size() < 6){
            display.setText("You don't have six courses yet. Try again later.");
            return;
        }
        
        // Average Calculation when assuming the ktca sections are weighted equally
        for (String course : topCourses) {
            double dailyMark = 0;
            double culminatingMark = 0;
            double dailyWeight = 0;
            double culminatingWeight = 0;
            for (Mark item : markArr){
                if (course.equals(item.getCourseCode())) {
		dailyMark = dailyMark + item.getKMark() / item.getKMaxMark() * item.getKWeight();
		dailyMark = dailyMark + item.getTMark() / item.getTMaxMark() * item.getTWeight();
		dailyMark = dailyMark + item.getCMark() / item.getCMaxMark() * item.getCWeight();
		dailyMark = dailyMark + item.getAMark() / item.getAMaxMark() * item.getAWeight();
                dailyWeight = dailyWeight + item.getKWeight() + item.getTWeight() + item.getCWeight() + item.getAWeight();
                 
		culminatingMark = culminatingMark + item.getCulminatingMark() / item.getCulminatingMaxMark() * item.getCulminatingWeight();
                culminatingWeight = culminatingWeight + item.getCulminatingWeight();
		}
            }
            double dailyAverage = dailyMark / dailyWeight * 100;
            double culminatingAverage = culminatingMark / culminatingWeight * 100;
            double courseAverage = dailyAverage * 0.7 + culminatingAverage * 0.3;
            topAverages.add(courseAverage);
	}
        
        for (int i = 0; i < 6; i++){
            overallAverage += topAverages.get(i);
            text += "Course code: " + topCourses.get(i) + " ";
            text += String.format("Course Average: %.1f\n", topAverages.get(i));
        }
        
        overallAverage =  overallAverage / 6;
        text += String.format("Overall Average: %.1f\n", overallAverage);
        
        display.setText(text);
    }//GEN-LAST:event_top6AverageButtonActionPerformed

    private void recursiveQuickSort(int low, int high) {
        if (low < high) {
            int pi = partition(low, high);
            recursiveQuickSort(low, pi - 1);
            recursiveQuickSort(pi + 1, high);
        }
    }

    private int partition(int low, int high) {
        double pivot = topAverages.get(high);
        int i = low - 1;
        for (int j = low; j < high; j++) {
            if (topAverages.get(j) > pivot) {
                i++;
                Collections.swap(topAverages, i, j);
                Collections.swap(topCourses, i, j);
            }
        }
        Collections.swap(topAverages, i + 1, high);
        Collections.swap(topCourses, i + 1, high);
        return i + 1;
    }
    
    // Method for string error checking
    public static boolean stringCheck(String str) {
        // Check for empty string, true represent the string has errors
	if (str == null || str.isEmpty()) {
	    return true;
	}
        // Try to parse the string as an integer
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
        // If parse integer is false, try parse double
            try {
                Double.parseDouble(str);
                return true;
            } catch (NumberFormatException ex) {
                // Return false for no errors found
                return false;
            }
        }
    }
	
    // Error check for if the user's input assignment already exists
    public static boolean assignmentExists(String code, String name) {
        // Loop through each item in the array list
        for (int i = 0; i < markArr.size(); i++) {
            Mark item = markArr.get(i);
            
            // Check if there are any matching names
            if (item.getCourseCode().equalsIgnoreCase(code) && item.getAssignmentName().equalsIgnoreCase(name)) {
                return true;
            }
        }
        // Return false as the input does not match any existing names
        return false;
    }
        
    // Method to check errors in doubles
    public static boolean invalidDecimal(double num) {
    	// Find the index of the decimal point
    	int dotIndex = String.valueOf(num).indexOf("."); 
    	
    	// Check for negative, true represent an error has occurred
    	if (num < 0) {
            return true;
    	}
        
    	// Exit case for when there is no decimal digits
        if (dotIndex == -1) {
            return false;
        }
     
        // Calculate the number of characters after the decimal point and compare 
        int decimalCount = String.valueOf(num).length() - dotIndex - 1;
        return decimalCount > 2;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });

        try {
            arrayAdder();
        } catch (IOException e) {
            throw new RuntimeException(e);

        }
    }
    
    public static class Mark {
	    private String courseCode;
	    private String assignmentName;
	    
	    private double kMark;
	    private double kMaxMark;
	    private double kWeight;
	    
	    private double tMark;
	    private double tMaxMark;
	    private double tWeight;
	    
	    private double cMark;
	    private double cMaxMark;
	    private double cWeight;
	    
	    private double aMark;
	    private double aMaxMark;
	    private double aWeight;
	    
	    private double culminatingMark;
	    private double culminatingMaxMark;
	    private double culminatingWeight;
	    
	    // Constructor 
	    public Mark(String courseCode, String assignmentName, double kMark, double kMaxMark, double kWeight, double tMark, 
	    			double tMaxMark, double tWeight, double cMark, double cMaxMark, double cWeight, double aMark,
	                double aMaxMark, double aWeight, double culminatingMark, double culminatingMaxMark, double culminatingWeight) {
	    	
	        this.courseCode = courseCode;
	        this.assignmentName = assignmentName;
	        
	        this.kMark = kMark;
	        this.kMaxMark = kMaxMark;
	        this.kWeight = kWeight;
	        
	        this.tMark = tMark;
	        this.tMaxMark = tMaxMark;
	        this.tWeight = tWeight;
	        
	        this.cMark = cMark;
	        this.cMaxMark = cMaxMark;
	        this.cWeight = cWeight;
	        
	        this.aMark = aMark;
	        this.aMaxMark = aMaxMark;
	        this.aWeight = aWeight;
	        
	        this.culminatingMark = culminatingMark;
	        this.culminatingMaxMark = culminatingMaxMark;
	        this.culminatingWeight = culminatingWeight;
	    }

	    // Getter and Setter for courseCode
	    public String getCourseCode() {
	        return courseCode;
	    }

	    public void setCourseCode(String courseCode) {
	        this.courseCode = courseCode;
	    }
	    
	    // Getter and Setter for assignmentName
	    public String getAssignmentName() {
	        return assignmentName;
	    }

	    public void setAssignmentName(String assignmentName) {
	        this.assignmentName = assignmentName;
	    }

	    // Getter and Setter for kMark
	    public double getKMark() {
	        return kMark;
	    }

	    public void setKMark(double kMark) {
	        this.kMark = kMark;
	    }
	    
	    // Getter and Setter for kMaxMark
	    public double getKMaxMark() {
	        return kMaxMark;
	    }

	    public void setKMaxMark(double kMaxMark) {
	        this.kMaxMark = kMaxMark;
	    }
	    
	    // Getter and Setter for kWeight
	    public double getKWeight() {
	        return kWeight;
	    }

	    public void setKWeight(double kWeight) {
	        this.kWeight = kWeight;
	    }

	    // Getter and Setter for tMark
	    public double getTMark() {
	        return tMark;
	    }

	    public void setTMark(double tMark) {
	        this.tMark = tMark;
	    }
	    
	    // Getter and Setter for tMaxMark
	    public double getTMaxMark() {
	        return tMaxMark;
	    }

	    public void setTMaxMark(double tMaxMark) {
	        this.tMaxMark = tMaxMark;
	    }

	    // Getter and Setter for tWeight
	    public double getTWeight() {
	        return tWeight;
	    }

	    public void setTWeight(double tWeight) {
	        this.tWeight = tWeight;
	    }

	    // Getter and Setter for cMark
	    public double getCMark() {
	        return cMark;
	    }

	    public void setCMark(double cMark) {
	        this.cMark = cMark;
	    }
	    
	    // Getter and Setter for cMaxMark
	    public double getCMaxMark() {
	        return cMaxMark;
	    }

	    public void setCMaxMark(double cMaxMark) {
	        this.cMaxMark = cMaxMark;
	    }

	    // Getter and Setter for cWeight
	    public double getCWeight() {
	        return cWeight;
	    }

	    public void setCWeight(double cWeight) {
	        this.cWeight = cWeight;
	    }

	    // Getter and Setter for aMark
	    public double getAMark() {
	        return aMark;
	    }

	    public void setAMark(double aMark) {
	        this.aMark = aMark;
	    }
	    
	    // Getter and Setter for aMaxMark
	    public double getAMaxMark() {
	        return aMaxMark;
	    }

	    public void setAMaxMark(double aMaxMark) {
	        this.aMaxMark = aMaxMark;
	    }

	    // Getter and Setter for aWeight
	    public double getAWeight() {
	        return aWeight;
	    }

	    public void setAWeight(double aWeight) {
	        this.aWeight = aWeight;
	    }

	    // Getter and Setter for culminatingMark
	    public double getCulminatingMark() {
	        return culminatingMark;
	    }

	    public void setCulminatingMark(double culminatingMark) {
	        this.culminatingMark = culminatingMark;
	    }
	    
	    // Getter and Setter for culminatingMark
	    public double getCulminatingMaxMark() {
	        return culminatingMaxMark;
	    }

	    public void setCulminatingMaxMark(double culminatingMaxMark) {
	        this.culminatingMaxMark = culminatingMaxMark;
	    }

	    // Getter and Setter for culminatingWeight
	    public double getCulminatingWeight() {
	        return culminatingWeight;
	    }
	    
	    public void setCulminatingWeight(double culminatingWeight) {
	        this.culminatingWeight = culminatingWeight;
	    }
	    
	    public String toString() {
	    	return String.format("%s,%s,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f,%.1f",
                    courseCode, assignmentName, kMark, kMaxMark, kWeight, tMark, tMaxMark, tWeight, cMark,
                    cMaxMark, cWeight, aMark, aMaxMark, aWeight, culminatingMark, culminatingMaxMark, culminatingWeight);
	    }
	        
	}

    // When opening/changing the ui, it will change the projected static elements, which breaks the searchMark.
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addMarkButton;
    private java.awt.Button courseAverageButton;
    private javax.swing.JScrollPane courseCodeField;
    protected static javax.swing.JTextArea courseCodeTextField;
    protected static javax.swing.JTextArea display;
    private java.awt.Button displayMarkButton;
    private java.awt.Button exitButton;
    private javax.swing.JScrollPane givenApplicationField;
    private javax.swing.JTextArea givenApplicationTextField;
    private javax.swing.JTextArea givenCommunicationTextField;
    private javax.swing.JTextArea givenCulminatingTextField;
    private javax.swing.JScrollPane givenKnowleadgeField;
    private javax.swing.JTextArea givenKnowledgeTextField;
    private javax.swing.JScrollPane givenThinkingField;
    private javax.swing.JTextArea givenThinkingTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTextArea maxApplicationTextField;
    private javax.swing.JScrollPane maxCommunicationField;
    private javax.swing.JScrollPane maxCommunicationField1;
    private javax.swing.JScrollPane maxCommunicationField2;
    private javax.swing.JTextArea maxCommunicationTextField;
    private javax.swing.JTextArea maxCulminatingTextField;
    private javax.swing.JScrollPane maxKnowleadgeField;
    private javax.swing.JScrollPane maxKnowleadgeField1;
    private javax.swing.JTextArea maxKnowledgeTextField;
    private javax.swing.JScrollPane maxThinkingFIeld;
    private javax.swing.JScrollPane maxThinkingFIeld1;
    private javax.swing.JTextArea maxThinkingTextField;
    private javax.swing.JScrollPane nameField;
    protected static javax.swing.JTextArea nameTextField;
    private java.awt.Button overallAverageButton;
    private java.awt.Button removeMarkButton;
    private java.awt.Button searchMarkButton;
    private java.awt.Button top6AverageButton;
    private javax.swing.JTextArea weightApplicationTextField;
    private javax.swing.JScrollPane weightCommunicationField;
    private javax.swing.JScrollPane weightCommunicationField1;
    private javax.swing.JTextArea weightCommunicationTextField;
    private javax.swing.JScrollPane weightCulminatingField;
    private javax.swing.JTextArea weightCulminatingTextField;
    private javax.swing.JTextArea weightKnowledgeTextField;
    private javax.swing.JTextArea weightThinkingTextField;
    // End of variables declaration//GEN-END:variables
}
